import Image from "next/image";

// The card media for a project: a desktop screenshot filling the frame with
// the same screen's mobile capture overlapping from the bottom-right corner.
// Decorative inside a linked card — the Link carries the accessible name, so
// both images stay empty-alt and the whole thing is aria-hidden.
// Assets are always /shots/{slug}/card-d.webp + card-m.webp
// (regenerated by scripts/shots-capture.mjs + shots-process.mjs).
type Props = {
  slug: string;
  sizes?: string; // next/image sizes for the desktop layer
  priority?: boolean; // above-the-fold usage (case-study hero)
};

export function CardStill({
  slug,
  sizes = "(max-width: 767px) 92vw, 640px",
  priority = false,
}: Props) {
  return (
    <span className="still" aria-hidden="true">
      <Image
        src={`/shots/${slug}/card-d.webp`}
        alt=""
        fill
        sizes={sizes}
        priority={priority}
        className="still-d"
      />
      <span className="still-m">
        <Image
          src={`/shots/${slug}/card-m.webp`}
          alt=""
          fill
          sizes="160px"
          className="still-m-img"
        />
      </span>
    </span>
  );
}
