// Typed project data, modeled from docs/PROJECTS.md.
// Used by the home orbit carousel, /work, and /work/[slug].
// Client-data guardrail: `confidential` projects show anonymized, dummy
// content only — never real client names or case data.

export type Capability = "ai" | "fullstack" | "design" | "client";
export type Visibility = "public" | "confidential";

// Status shown on the /work card media: a live site, or a guardrail marker for
// confidential projects (anonymized screens / fully confidential).
export type ProjectStatus = "live" | "anonymized" | "confidential";

// One case-study gallery slide. Assets live in public/shots/{slug}/ and are
// regenerated by scripts/shots-capture.mjs + shots-process.mjs.
export type Shot = {
  src: string;
  alt: string; // what a screen reader gets instead of the image
  caption: string; // names the feature on screen, shown under the slide
};

export type Project = {
  slug: string;
  title: string;
  tagline: string;
  capabilities: Capability[];
  stack: string[];
  role: string; // short form, shown in the case-study meta row
  roleDetail: string; // full prose for the "My role" section
  problem: string;
  whatIBuilt: string;
  outcomes: string;
  links: { live?: string; repo?: string };
  visibility: Visibility;
  featured?: boolean;
  // Home / Work index display fields
  year: number;
  live?: boolean; // show the "● Live" marker
  tags: string[]; // short display tags (the case study carries the full stack)
  // /work page display fields
  description: string; // one-to-two sentence card blurb
  category: string; // mono category line, e.g. "AI Product · Full-Stack"
  mediaCaption: string; // small caption inside the card visual
  status?: ProjectStatus; // dot marker on the visual (omit for none)
  // Case-study gallery slides. The card still is always
  // /shots/{slug}/card-d.webp + card-m.webp and needs no per-project config.
  shots: Shot[];
};

export const projects: Project[] = [
  {
    slug: "farewise",
    title: "FareWise",
    tagline:
      "Flight search that returns live fares and explains each one in plain language.",
    capabilities: ["ai", "fullstack"],
    stack: ["Next.js", "TypeScript", "Claude API", "SerpApi"],
    role: "Design and build, end to end.",
    roleDetail:
      "Solo, end to end: the product concept, the interface, and the full build. That includes the SerpApi integration and the prompt design behind the per-fare analysis.",
    problem:
      "A fare list ranks prices. The reasons a cheap fare is cheap — two stops each way, an overnight arrival, a price so low the airline may cancel it — sit in the fine print, and that is where bad bookings happen.",
    whatIBuilt:
      "A round-trip search backed by live SerpApi fare data. Claude reads the results and writes the honest read: what each fare trades away, whether the price is typical for the route, and a warning when a fare looks like a mistake the airline can cancel.",
    outcomes:
      "Two live integrations rather than mocked data: SerpApi returns the fares, Claude writes the read on each one. The route summary states the typical price range, and suspiciously low fares carry an explicit mistake-fare warning.",
    links: { repo: "https://github.com/randall-flores/farewise" },
    visibility: "public",
    featured: true,
    year: 2026,
    tags: ["AI Product", "Claude API", "SerpApi"],
    description:
      "Flight search with live fares. SerpApi supplies the results, Claude explains each fare's trade-offs and flags likely mistake fares.",
    category: "AI Product · Full-Stack · API Integration",
    mediaCaption: "FareWise — Live fare results",
    shots: [
      {
        src: "/shots/farewise/g-results.webp",
        alt: "FareWise results for San José to New York: five live fares and Claude's plain-language read of each one",
        caption: "Live SerpApi fares with Claude's per-fare read",
      },
      {
        src: "/shots/farewise/g-results-deep.webp",
        alt: "The cheapest fare card with route, stops, and an explicit warning that the price may be a mistake fare the airline can cancel",
        caption: "The mistake-fare warning on a suspiciously cheap result",
      },
    ],
  },
  {
    slug: "vox",
    title: "Vox",
    tagline:
      "Production site for a German voice-over actress, with a custom liquid-glass design system and bilingual routing.",
    capabilities: ["design", "client"],
    stack: ["Next.js", "Tailwind", "framer-motion", "i18n (EN/DE)", "Vercel"],
    role: "Design and build for a client, in production.",
    roleDetail:
      "Design and build for a client: the visual identity, the design system, and the full Next.js implementation through to the production deploy on Vercel.",
    problem:
      "A working voice-over actress needed a presence that carried her brand in both English and German and satisfied German legal requirements. The site is where prospective clients form their first impression of her work.",
    whatIBuilt:
      "A custom liquid-glass design system with magnetic hover interactions, bilingual EN/DE routing, and the German legal compliance pages (Impressum, Datenschutz). Built on Next.js with Tailwind and framer-motion.",
    outcomes:
      "Live in production. The design system holds across both languages, and the Impressum and Datenschutz pages cover what German law requires of a professional site.",
    links: { live: "https://vox-voiceover.vercel.app" },
    visibility: "public",
    year: 2026,
    tags: ["Voice-over", "Design System", "EN/DE"],
    description:
      "Production site for a German voice-over actress. A custom liquid-glass design system, magnetic interactions, bilingual routing, and German legal compliance pages.",
    category: "Client · Design System · EN/DE",
    mediaCaption: "Vox — Production site",
    shots: [
      {
        src: "/shots/vox/g-demos.webp",
        alt: "Demos page with playable voice-over samples",
        caption: "Demos, with playable samples",
      },
      {
        src: "/shots/vox/g-credits.webp",
        alt: "Credits page listing dubbing and voice-over filmography",
        caption: "Credits filmography",
      },
    ],
  },
  {
    slug: "hollow-ronin",
    title: "Hollow Ronin",
    tagline:
      "Drop-based streetwear brand built end to end on headless commerce, with AI-generated art.",
    capabilities: ["design", "fullstack"],
    stack: ["Headless Shopify", "Printify", "Next.js", "Midjourney", "Adobe Firefly"],
    role: "Founder, designer, developer. End-to-end brand and store.",
    roleDetail:
      "Founder, designer, and developer. The brand identity, the art direction, the storefront build, and the product pipeline, all of it solo.",
    problem:
      "Launch a drop-based streetwear brand with a strong identity and a working storefront, solo. That means brand design, a product pipeline, and commerce infrastructure with no team behind any of it.",
    whatIBuilt:
      "A headless Shopify storefront with Printify handling fulfillment, the full brand identity, and an art pipeline where Midjourney and Adobe Firefly generate and refine the artwork behind each drop.",
    outcomes:
      "A live store built end to end: headless Shopify wired to Printify for fulfillment, a coherent brand, and Midjourney and Firefly generating the artwork behind each drop.",
    links: {
      live: "https://hollowronin.com",
      repo: "https://github.com/randall-flores/hollow-ronin",
    },
    visibility: "public",
    year: 2026,
    tags: ["Headless Shopify", "Printify", "Brand"],
    description:
      "A drop-based streetwear brand built end to end on headless Shopify and Printify, with AI-generated art driving the visual identity.",
    category: "Brand · Headless Commerce · Design",
    mediaCaption: "Hollow Ronin — Drop store",
    shots: [
      {
        src: "/shots/hollow-ronin/g-shop.webp",
        alt: "Shop page: The Armory, category tiles for tees, shirts, hoodies, joggers and outerwear",
        caption: "The Armory, shop categories",
      },
      {
        src: "/shots/hollow-ronin/g-product.webp",
        alt: "Product page for the Ryūjin tee: gallery, character lore, price, size picker",
        caption: "Product page, Ryūjin tee",
      },
      {
        src: "/shots/hollow-ronin/g-lookbook.webp",
        alt: "Lookbook editorial page",
        caption: "Lookbook, Editorial Vol. I",
      },
    ],
  },
  {
    slug: "adrift",
    title: "Adrift",
    tagline:
      "A hand-curated product discovery feed: the products you scrolled past, kept in one place.",
    capabilities: ["fullstack", "design"],
    stack: ["Next.js", "TypeScript", "Supabase", "Vercel"],
    role: "Design and build, end to end.",
    roleDetail:
      "Solo: the brand, the feed design, the Supabase data model, and the curation workflow behind it.",
    problem:
      "Products surface mid-scroll and vanish. A week later the brand name is gone, and the search terms that would find it again are gone with it.",
    whatIBuilt:
      "A curated feed on Next.js and Supabase: a weekly drop of picks, a daily rotation, category filters across seven verticals, product pages that link straight to the brand's own store, and saves. Every product is added by hand.",
    outcomes:
      "Live on Vercel. The weekly drop carries eight picks, the daily rotation changes on schedule, and every product page resolves to the brand's real storefront.",
    links: {
      live: "https://adspotted.vercel.app",
      repo: "https://github.com/randall-flores/adspotted",
    },
    visibility: "public",
    year: 2026,
    tags: ["Product Feed", "Supabase", "Curation"],
    description:
      "A hand-curated product discovery feed. A weekly drop and a daily rotation across seven categories, built on Next.js and Supabase.",
    category: "Full-Stack · Product Feed · Design",
    mediaCaption: "Adrift — Discovery feed",
    shots: [
      {
        src: "/shots/adrift/g-find.webp",
        alt: "Adrift product page for a wireless mouse with a direct shop link",
        caption: "Product page with a direct shop link",
      },
      {
        src: "/shots/adrift/g-explore.webp",
        alt: "Adrift explore view with category browsing",
        caption: "Explore, browsing by category",
      },
    ],
  },
  {
    slug: "sana",
    title: "Sana",
    tagline:
      "A bilingual personal-injury companion app. Full-stack, auth, internationalized.",
    capabilities: ["fullstack"],
    stack: ["Next.js", "Tailwind", "shadcn/ui", "next-intl", "Supabase (RLS)"],
    role: "Full-stack design and build.",
    roleDetail:
      "Full-stack design and build: the information architecture, the interface, the auth and data-access model, and the bilingual content structure.",
    problem:
      "Personal-injury clients are anxious and underinformed, and many navigate the process in Spanish while the paperwork happens in English. They need a calm, bilingual companion that explains where their case stands and what happens next.",
    whatIBuilt:
      "A bilingual (EN/ES) companion app built on Next.js and shadcn/ui, internationalized with next-intl. Supabase handles authentication with row-level security, so each client can only ever reach their own data.",
    outcomes:
      "Row-level security is enforced in Postgres rather than trusted to the UI, so a client can only ever reach their own records. The i18n structure keeps full parity across both languages.",
    links: { repo: "https://github.com/randall-flores/sana.app" },
    visibility: "confidential",
    year: 2026,
    tags: ["Full-stack", "Supabase RLS", "next-intl"],
    description:
      "A bilingual personal-injury companion app. Next.js front to back, Supabase auth with row-level security, and next-intl for EN/ES. Screens anonymized.",
    category: "Full-Stack · Auth · i18n",
    mediaCaption: "Sana — Anonymized",
    status: "anonymized",
    shots: [
      {
        src: "/shots/sana/g-es-hero.webp",
        alt: "Sana landing page in Spanish: Sana, recuerda, recupérate",
        caption: "The same page in the Spanish locale, full next-intl parity",
      },
      {
        src: "/shots/sana/g-features.webp",
        alt: "Three feature cards: document everything, track your recovery, know what's happening with your case",
        caption: "The three jobs: documents, recovery, case status",
      },
      {
        src: "/shots/sana/g-signin.webp",
        alt: "Sana sign-in screen backed by Supabase auth",
        caption: "Sign-in, Supabase auth with row-level security behind it",
      },
    ],
  },
  {
    slug: "caseflow",
    title: "Caseflow",
    tagline:
      "Case management and records-request automation for a law firm, replacing repeated manual data entry.",
    capabilities: ["fullstack", "client"],
    stack: ["Next.js", "React", "TypeScript", "Tailwind", "PDF generation", "Vercel"],
    role: "Design and build of an internal firm tool.",
    roleDetail:
      "Design and build of an internal tool for a law firm, from mapping the existing workflow with the people running it to the version the firm ran in production.",
    problem:
      "A law firm's records-request and case-management workflow was repetitive and manual: the same client details re-entered across forms, letters, and requests, and every re-entry was another chance for a typo in a legal document.",
    whatIBuilt:
      "Records-request automation, document generation, and case management. Client details are entered once and flow into every generated packet.",
    outcomes:
      "Ran in production at the firm: generated document packets replaced hand-assembled ones, and client details were entered once instead of re-keyed across every form.",
    links: {},
    visibility: "confidential",
    year: 2025,
    tags: ["Internal", "Doc Automation", "Confidential"],
    description:
      "Case management and records-request automation for a law firm. Generates the document packets and removes the repeated data entry from the workflow. Fully anonymized.",
    category: "Internal · Workflow · Document Automation",
    mediaCaption: "Internal tool — Confidential",
    status: "confidential",
    shots: [
      {
        src: "/shots/caseflow/g-treatment.webp",
        alt: "Treatment report tab: upload medical PDFs, treatment dates extracted into a report",
        caption: "Treatment report: PDFs in, treatment dates out",
      },
      {
        src: "/shots/caseflow/g-records.webp",
        alt: "Records requests tab: provider selected and a HIPAA packet being assembled",
        caption: "Records requests: provider selected, packet assembled",
      },
    ],
  },
];
